version: '3'
services:
  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    volumes:
      - ./data:/var/lib/influxdb
    environment:
      INFLUXDB_DB: events
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_HTTP_FLUX_ENABLED: 'true'
  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    container_name: grafana
  scraper:
    build: .
    environment:
      INFLUXDB_HOST: 'influxdb:8086'
      INFLUXDB_TOKEN: 'admin:admin'
      CLASH_HOST: '192.168.1.5:9090'
      CLASH_TOKEN: '123456'
    container_name: scraper
